### ISSUE TITLE
Typo at line 468

### ISSUE THREAD

**Issue by Kat-zorn** [ALVAROPING1/Trailmakers-LogicBlocksGuide#6]
**Describe the error**
The line says:  
> When something is activated, it acts as if you pressed the keybind. Positive values act as the green keybind and negative values act as the red keybind. For things that only have green keybind, the absolute value will be used

And "For things that only have green keybind" isn't quite right, I would propose "For things that only have a green keybind" or "For things that only have green keybinds".

**Location**
line 468

**Additional context**
nope

**Comment by ALVAROPING1** [comment]
I have fixed the issue in the dev branch. I decided to go with "a green keybind" rather than "green keybinds" as blocks can't have more than 1 green keybind
